version: 2.1

commands:
  test:
    parameters:
      php_version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-<< parameters.php_version >>-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: vendor-<< parameters.php_version >>-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: ./vendor/bin/phpunit --stop-on-failure

executors:
  php:
    parameters:
      php_version:
        type: string
    docker:
      - image: circleci/php:<< parameters.php_version >>

jobs:
  test_php73:
    executor:
      name: php
      php_version: "7.3"
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-7.3-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpcs --standard=.phpcs.xml src
      - run: ./vendor/bin/phpcs --standard=.phpcs.xml spec --exclude="PSR1.Methods.CamelCapsMethodName"
      - run: ./vendor/bin/phpcs --standard=.phpcs.xml tests
      - run: ./vendor/bin/phpspec run
      - run: ./vendor/bin/phpunit --stop-on-failure --coverage-clover 'reports/clover.xml' --log-junit 'reports/php-junit.xml'
      - persist_to_workspace:
          root: .
          paths:
            - .
  sonar_scan:
    docker:
      - image: gcr.io/opnf-management/sonar-scanner:latest
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run: /opt/run-scan.sh
  test_php56:
    executor:
      name: php
      php_version: "5.6"
    steps:
      - test:
          php_version: "5.6"
  test_php70:
    executor:
      name: php
      php_version: "7.0"
    steps:
      - test:
          php_version: "7.0"
  test_php71:
    executor:
      name: php
      php_version: "7.1"
    steps:
      - test:
          php_version: "7.1"
  test_php72:
    executor:
      name: php
      php_version: "7.2"
    steps:
      - test:
          php_version: "7.2"

workflows:
  version: 2
  build:
    jobs:
      - test_php56
      - test_php70
      - test_php71
      - test_php72
      - test_php73
      - sonar_scan:
          context: shared-secrets
          requires:
            - test_php73
